// auth
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD'
export const AUTH_CHANGE_PASSWORD_START = 'AUTH_CHANGE_PASSWORD_START'
export const AUTH_CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS'
export const AUTH_CHANGE_PASSWORD_FAIL = 'AUTH_CHANGE_PASSWORD_FAIL'

export const AUTH_CREATE_ACCOUNT = 'AUTH_CREATE_ACCOUNT'
export const AUTH_CREATE_ACCOUNT_START = 'AUTH_CREATE_ACCOUNT_START'
export const AUTH_CREATE_ACCOUNT_SUCCESS = 'AUTH_CREATE_ACCOUNT_SUCCESS'
export const AUTH_CREATE_ACCOUNT_FAIL = 'AUTH_CREATE_ACCOUNT_FAIL'


// ux
export const TOGGLE_SIDEDRAWER =  'TOGGLE_SIDEDRAWER'
export const TOGGLE_LOGIN_MODAL =  'TOGGLE_LOGIN_MODAL'
export const TOGGLE_REGISTER_MODAL =  'TOGGLE_REGISTER_MODAL'

// userdocks
export const GET_USER_DOCKS_START =  'GET_USER_DOCKS_START'
export const GET_USER_DOCKS_SUCCESS =  'GET_USER_DOCKS_SUCCESS'
export const GET_USER_DOCKS_FAIL =  'GET_USER_DOCKS_FAIL'

export const ADD_USER_DOCK_START =  'ADD_USER_DOCK_START'
export const ADD_USER_DOCK_SUCCESS =  'ADD_USER_DOCK_SUCCESS'
export const ADD_USER_DOCK_FAIL =  'ADD_USER_DOCK_FAIL'

export const REMOVE_USER_DOCK_START =  'REMOVE_USER_DOCK_START'
export const REMOVE_USER_DOCK_SUCCESS =  'REMOVE_USER_DOCK_SUCCESS'
export const REMOVE_USER_DOCK_FAIL =  'REMOVE_USER_DOCK_FAIL'

// docks
export const GET_ALL_DOCKS_START =  'GET_ALL_DOCKS_START'
export const GET_ALL_DOCKS_SUCCESS =  'GET_ALL_DOCKS_SUCCESS'
export const GET_ALL_DOCKS_FAIL =  'GET_ALL_DOCKS_FAIL'

export const REMOVE_DOCK_START =  'REMOVE_DOCK_START'
export const REMOVE_DOCK_SUCCESS =  'REMOVE_DOCK_SUCCESS'
export const REMOVE_DOCK_FAIL =  'REMOVE_DOCK_FAIL'

export const ADD_DOCK_START =  'ADD_DOCK_START'
export const ADD_DOCK_SUCCESS =  'ADD_DOCK_SUCCESS'
export const ADD_DOCK_FAIL =  'ADD_DOCK_FAIL'

export const GET_DOCK_WITH_ADDRESS_BY_ID_START =  'GET_DOCK_WITH_ADDRESS_BY_ID_START'
export const GET_DOCK_WITH_ADDRESS_BY_ID_SUCCESS =  'GET_DOCK_WITH_ADDRESS_BY_ID_SUCCESS'
export const GET_DOCK_WITH_ADDRESS_BY_ID_FAIL =  'GET_DOCK_WITH_ADDRESS_BY_ID_FAIL'

// address
export const GET_USER_ADDRESSES_START =  'GET_USER_ADDRESSES_START'
export const GET_USER_ADDRESSES_SUCCESS =  'GET_USER_ADDRESSES_SUCCESS'
export const GET_USER_ADDRESSES_FAIL =  'GET_USER_ADDRESSES_FAIL'

export const ADD_USER_ADDRESS_START =  'ADD_USER_ADDRESS_START'
export const ADD_USER_ADDRESS_SUCCESS =  'ADD_USER_ADDRESS_SUCCESS'
export const ADD_USER_ADDRESS_FAIL =  'ADD_USER_ADDRESS_FAIL'

