// auth
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const LOGIN_USER =  'LOGIN_USER'
export const LOGOUT_USER =  'LOGOUT_USER'

// ux
export const TOGGLE_SIDEDRAWER =  'TOGGLE_SIDEDRAWER'
export const TOGGLE_LOGIN_MODAL =  'TOGGLE_LOGIN_MODAL'
export const TOGGLE_REGISTER_MODAL =  'TOGGLE_REGISTER_MODAL'
export const TOGGLE_FORGOTPASSWORD_MODAL =  'TOGGLE_FORGOTPASSWORD_MODAL'

// dock

export const GET_USER_DOCKS_START =  'GET_USER_DOCKS_START'
export const GET_USER_DOCKS_SUCCESS =  'GET_USER_DOCKS_SUCCESS'
export const GET_USER_DOCKS_FAIL =  'GET_USER_DOCKS_FAIL'

export const GET_ALL_DOCKS_START =  'GET_ALL_DOCKS_START'
export const GET_ALL_DOCKS_SUCCESS =  'GET_ALL_DOCKS_SUCCESS'
export const GET_ALL_DOCKS_FAIL =  'GET_ALL_DOCKS_SFAIL'

export const REMOVE_DOCK_START =  'REMOVE_DOCK_START'
export const REMOVE_DOCK_SUCCESS =  'REMOVE_DOCK_SUCCESS'
export const REMOVE_DOCK_FAIL =  'REMOVE_DOCK_FAIL'

export const ADD_DOCK_START =  'ADD_DOCK_START'
export const ADD_DOCK_SUCCESS =  'ADD_DOCK_SUCCESS'
export const ADD_DOCK_FAIL =  'ADD_DOCK_FAIL'

export const GET_DOCK_BY_ID =  'GET_DOCK_BY_ID'
