const countryCodes = () => {
    return [
        {value: 'AL', displayValue: 'Alabama'},
        {value: 'AK', displayValue: 'Alaska'},
        {value: 'AS', displayValue: 'American Samoa'},
        {value: 'AZ', displayValue: 'Arizona'},
        {value: 'AR', displayValue: 'Arkansas'},
        {value: 'CA', displayValue: 'California'},
        {value: 'CO', displayValue: 'Colorado'},
        {value: 'CT', displayValue: 'Connecticut'},
        {value: 'DE', displayValue: 'Delaware'},
        {value: 'DC', displayValue: 'District Of Columbia'},
        {value: 'FM', displayValue: 'Federated States Of Micronesia'},
        {value: 'FL', displayValue: 'Florida'},
        {value: 'GA', displayValue: 'Georgia'},
        {value: 'GU', displayValue: 'Guam'},
        {value: 'HI', displayValue: 'Hawaii'},
        {value: 'ID', displayValue: 'Idaho'},
        {value: 'IL', displayValue: 'Illinois'},
        {value: 'IN', displayValue: 'Indiana'},
        {value: 'IA', displayValue: 'Iowa'},
        {value: 'KS', displayValue: 'Kansas'},
        {value: 'KY', displayValue: 'Kentucky'},
        {value: 'LA', displayValue: 'Louisiana'},
        {value: 'ME', displayValue: 'Maine'},
        {value: 'MH', displayValue: 'Marshall Islands'},
        {value: 'MD', displayValue: 'Maryland'},
        {value: 'MA', displayValue: 'Massachusetts'},
        {value: 'MI', displayValue: 'Michigan'},
        {value: 'MN', displayValue: 'Minnesota'},
        {value: 'MS', displayValue: 'Mississippi'},
        {value: 'MO', displayValue: 'Missouri'},
        {value: 'MT', displayValue: 'Montana'},
        {value: 'NE', displayValue: 'Nebraska'},
        {value: 'NV', displayValue: 'Nevada'},
        {value: 'NH', displayValue: 'New Hampshire'},
        {value: 'NJ', displayValue: 'New Jersey'},
        {value: 'NM', displayValue: 'New Mexico'},
        {value: 'NY', displayValue: 'New York'},
        {value: 'NC', displayValue: 'North Carolina'},
        {value: 'ND', displayValue: 'North Dakota'},
        {value: 'MP', displayValue: 'Northern Mariana Islands'},
        {value: 'OH', displayValue: 'Ohio'},
        {value: 'OK', displayValue: 'Oklahoma'},
        {value: 'OR', displayValue: 'Oregon'},
        {value: 'PW', displayValue: 'Palau'},
        {value: 'PA', displayValue: 'Pennsylvania'},
        {value: 'PR', displayValue: 'Puerto Rico'},
        {value: 'RI', displayValue: 'Rhode Island'},
        {value: 'SC', displayValue: 'South Carolina'},
        {value: 'SD', displayValue: 'South Dakota'},
        {value: 'TN', displayValue: 'Tennessee'},
        {value: 'TX', displayValue: 'Texas'},
        {value: 'UT', displayValue: 'Utah'},
        {value: 'VT', displayValue: 'Vermont'},
        {value: 'VI', displayValue: 'Virgin Islands'},
        {value: 'VA', displayValue: 'Virginia'},
        {value: 'WA', displayValue: 'Washington'},
        {value: 'WV', displayValue: 'West Virginia'},
        {value: 'WI', displayValue: 'Wisconsin'},
        {value: 'WY', displayValue: 'Wyomin'}
    ]
}

export default countryCodes;
