"""empty message

Revision ID: e7e2d3e2c5a4
Revises: 
Create Date: 2020-06-06 13:35:50.646782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e2d3e2c5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('phonenumber', sa.Text(), nullable=False),
    sa.Column('mail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('phonenumber'),
    sa.UniqueConstraint('username')
    )
    op.create_table('address',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('addressid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('housenumber', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('postalcode', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('addressid')
    )
    op.create_table('dock',
    sa.Column('dockid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('addressid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('length', sa.Numeric(), nullable=False),
    sa.Column('width', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.Column('rented', sa.Boolean(), nullable=False),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['addressid'], ['address.addressid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('dockid')
    )
    op.create_table('rented',
    sa.Column('reservationid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenantid', sa.Integer(), nullable=False),
    sa.Column('dockid', sa.Integer(), nullable=False),
    sa.Column('reservationtimestamp', sa.Integer(), nullable=False),
    sa.Column('arrivaldate', sa.Text(), nullable=False),
    sa.Column('departuredate', sa.Text(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('paymentid', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dockid'], ['dock.dockid'], ),
    sa.ForeignKeyConstraint(['tenantid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('reservationid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rented')
    op.drop_table('dock')
    op.drop_table('address')
    op.drop_table('users')
    # ### end Alembic commands ###
