"""empty message

Revision ID: f2850705cc6d
Revises: 
Create Date: 2020-06-05 20:27:34.643095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2850705cc6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rented',
    sa.Column('reservationid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenantid', sa.Integer(), nullable=False),
    sa.Column('dockid', sa.Integer(), nullable=False),
    sa.Column('reservationtimestamp', sa.Integer(), nullable=False),
    sa.Column('arrivaldate', sa.Text(), nullable=False),
    sa.Column('departuredate', sa.Text(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dockid'], ['dock.dockid'], ),
    sa.ForeignKeyConstraint(['tenantid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('reservationid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rented')
    # ### end Alembic commands ###
